# Generated by Django 4.2.29 on 2026-04-09 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('units', 'Units'), ('grams', 'Grams'), ('kilograms', 'Kilograms'), ('milliliters', 'Milliliters'), ('liters', 'Liters'), ('teaspoons', 'Teaspoons'), ('tablespoons', 'Tablespoons'), ('cups', 'Cups'), ('slices', 'Slices'), ('packs', 'Packs'), ('cans', 'Cans'), ('bottles', 'Bottles'), ('pieces', 'Pieces')], default='units', max_length=20)),
                ('location', models.CharField(choices=[('FRIDGE', 'Fridge'), ('FREEZER', 'Freezer'), ('PANTRY', 'Pantry')], default='PANTRY', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'ingredient__name'],
                'permissions': [('mark_food_consumed', 'Can mark a food item as consumed'), ('mark_food_wasted', 'Can mark a food item as wasted')],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='app.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('source_site', models.CharField(blank=True, max_length=100)),
                ('is_preloaded', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='app.household')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('view_suggested_recipes', 'Can view suggested recipes')],
            },
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('units', 'Units'), ('grams', 'Grams'), ('kilograms', 'Kilograms'), ('milliliters', 'Milliliters'), ('liters', 'Liters'), ('teaspoons', 'Teaspoons'), ('tablespoons', 'Tablespoons'), ('cups', 'Cups'), ('slices', 'Slices'), ('packs', 'Packs'), ('cans', 'Cans'), ('bottles', 'Bottles'), ('pieces', 'Pieces')], default='units', max_length=20)),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('forgotten', 'Forgotten'), ('other', 'Other')], default='expired', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='app.food')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='app.household')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waste_logs', to='app.ingredient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('unit', models.CharField(blank=True, choices=[('units', 'Units'), ('grams', 'Grams'), ('kilograms', 'Kilograms'), ('milliliters', 'Milliliters'), ('liters', 'Liters'), ('teaspoons', 'Teaspoons'), ('tablespoons', 'Tablespoons'), ('cups', 'Cups'), ('slices', 'Slices'), ('packs', 'Packs'), ('cans', 'Cans'), ('bottles', 'Bottles'), ('pieces', 'Pieces')], max_length=20)),
                ('line_text', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_links', to='app.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='app.recipe')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('recipe', 'position')},
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='app.RecipeIngredient', to='app.ingredient'),
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='app.household')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_household_members', 'Can manage household members'), ('change_member_role', 'Can change household member role')],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='app.household'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='app.ingredient'),
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_text', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.recipe')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('recipe', 'position')},
            },
        ),
    ]
