# Generated by Django 5.2.12 on 2026-03-31 20:22

from django.db import migrations

def load_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')

    categories = [
        'Dairy',
        'Meat',
        'Fish',
        'Fruit',
        'Vegetables',
        'Bakery',
        'Drinks',
        'Snacks',
        'Frozen',
        'Pantry',
    ]

    for category_name in categories:
        Category.objects.get_or_create(name=category_name)


def unload_categories(apps, schema_editor):
    Category = apps.get_model('app', 'Category')

    categories = [
        'Dairy',
        'Meat',
        'Fish',
        'Fruit',
        'Vegetables',
        'Bakery',
        'Drinks',
        'Snacks',
        'Frozen',
        'Pantry',
    ]

    Category.objects.filter(name__in=categories).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
    ]
