# Generated from wasteless_recipes_500.json
from django.db import migrations


def load_ingredients(apps, schema_editor):
    Category = apps.get_model('app', 'Category')
    Ingredient = apps.get_model('app', 'Ingredient')

    ingredients = [
    ('after eight', 'Pantry'),
    ('all-butter puff pastry', 'Dairy'),
    ('allspice', 'Pantry'),
    ('allspice berry', 'Fruit'),
    ('almond', 'Snacks'),
    ('almond extract', 'Snacks'),
    ('almond milk', 'Dairy'),
    ('almond milk chocolate', 'Dairy'),
    ('amaretti biscuit', 'Snacks'),
    ('amaretto', 'Pantry'),
    ('amaretto liqueur', 'Drinks'),
    ('anchovy', 'Fish'),
    ('angostura bitter', 'Pantry'),
    ('apple', 'Fruit'),
    ('apple cider vinegar', 'Fruit'),
    ('apple juice', 'Fruit'),
    ('apricot', 'Fruit'),
    ('apricot jam', 'Fruit'),
    ('arrowroot', 'Pantry'),
    ('assorted food colouring', 'Pantry'),
    ('aubergine', 'Drinks'),
    ('avocado', 'Fruit'),
    ('baby beetroot', 'Vegetables'),
    ('baby leek', 'Vegetables'),
    ('baby onion', 'Vegetables'),
    ('baby spinach', 'Vegetables'),
    ('baby turnip', 'Vegetables'),
    ('back bacon', 'Meat'),
    ('bacon', 'Meat'),
    ('bacon lardon', 'Meat'),
    ('baconlardon', 'Meat'),
    ('baileyscream liqueur', 'Dairy'),
    ('baking powder', 'Pantry'),
    ('balsamic vinegar', 'Pantry'),
    ('banana', 'Fruit'),
    ('banana shallot', 'Fruit'),
    ('basil', 'Vegetables'),
    ('basmati rice', 'Pantry'),
    ('basmati wild ricemix', 'Pantry'),
    ('bavarian smoked cheese', 'Dairy'),
    ('bay leaf', 'Vegetables'),
    ('beansprout', 'Vegetables'),
    ('beef fillet', 'Meat'),
    ('beef stock', 'Meat'),
    ('beef stock cube', 'Meat'),
    ('beef suet', 'Meat'),
    ('beetroot', 'Vegetables'),
    ('berries', 'Fruit'),
    ('bicarbonate of soda', 'Pantry'),
    ("bird's custard powder", 'Dairy'),
    ("bird's-eye chilli", 'Vegetables'),
    ('black fondant', 'Pantry'),
    ('black mustard seed', 'Pantry'),
    ('black olive', 'Pantry'),
    ('black pepper', 'Vegetables'),
    ('black peppercorn', 'Vegetables'),
    ('black pudding', 'Meat'),
    ('black treacle', 'Pantry'),
    ('black writing icing', 'Pantry'),
    ('blackberry', 'Fruit'),
    ('blade mace', 'Pantry'),
    ('blanched almond', 'Snacks'),
    ('blanched hazelnut', 'Snacks'),
    ('blanched whole almond', 'Snacks'),
    ('blood orange', 'Fruit'),
    ('blue cheese', 'Dairy'),
    ('blue food colouringpaste', 'Pantry'),
    ('blueberry conserve', 'Fruit'),
    ('boiling water', 'Drinks'),
    ('bok choi', 'Pantry'),
    ('bouquet garni', 'Vegetables'),
    ('bourbon', 'Pantry'),
    ('boursin cheese', 'Dairy'),
    ('bovril', 'Pantry'),
    ('bramley apple', 'Fruit'),
    ('bramley apple sauce', 'Fruit'),
    ('brandy', 'Drinks'),
    ('bread mix', 'Bakery'),
    ('breadcrumb', 'Bakery'),
    ('brie', 'Pantry'),
    ('brioche roll', 'Bakery'),
    ('broad bean', 'Vegetables'),
    ('brown bread', 'Bakery'),
    ('brown lentil', 'Vegetables'),
    ('brown sugar', 'Pantry'),
    ('brussels sprout', 'Vegetables'),
    ('buckwheat flour', 'Pantry'),
    ('burger bun', 'Bakery'),
    ('butter', 'Dairy'),
    ('buttermilk', 'Dairy'),
    ('butternut squash', 'Dairy'),
    ('button mushroom', 'Vegetables'),
    ('cabbage', 'Vegetables'),
    ('caerphilly cheese', 'Dairy'),
    ('calvado', 'Drinks'),
    ('camembert', 'Pantry'),
    ('canapé blinis', 'Pantry'),
    ('caper', 'Pantry'),
    ('caramel', 'Dairy'),
    ('caraway seed', 'Pantry'),
    ('cardamom pod', 'Pantry'),
    ('carrot', 'Vegetables'),
    ('cashew nut', 'Snacks'),
    ('cassis', 'Pantry'),
    ('caster sugar', 'Pantry'),
    ('cauliflower', 'Vegetables'),
    ('caviarjacket', 'Pantry'),
    ('cayenne pepper', 'Vegetables'),
    ('celeriac', 'Pantry'),
    ('celery', 'Vegetables'),
    ('celery salt', 'Vegetables'),
    ('chamomile teabag', 'Meat'),
    ('champagne', 'Meat'),
    ('chantenay carrot', 'Vegetables'),
    ('charentais melon', 'Fruit'),
    ('cheddar', 'Dairy'),
    ('cheese', 'Dairy'),
    ('cherries', 'Fruit'),
    ('cherry', 'Fruit'),
    ('cherry brandy', 'Fruit'),
    ('cherry tomato', 'Fruit'),
    ('chervil', 'Pantry'),
    ('chestnut', 'Snacks'),
    ('chestnut mushroom', 'Vegetables'),
    ('chicken', 'Meat'),
    ('chicken breast', 'Meat'),
    ('chicken stock', 'Meat'),
    ('chicken stock cube', 'Meat'),
    ('chicken thighson the bone', 'Meat'),
    ('chicken wing', 'Meat'),
    ('chickpea', 'Vegetables'),
    ('chicory', 'Pantry'),
    ('chilled champagne', 'Meat'),
    ('chilli', 'Vegetables'),
    ('chilli flake', 'Vegetables'),
    ('chilli sauce', 'Vegetables'),
    ('chinese five', 'Pantry'),
    ('chinese five spice', 'Pantry'),
    ('chipolatasausage', 'Meat'),
    ('chive', 'Pantry'),
    ('chocolate', 'Snacks'),
    ('chocolate button', 'Snacks'),
    ('chocolate chip', 'Snacks'),
    ('chocolate digestive biscuit', 'Snacks'),
    ('chocolate ice cream', 'Dairy'),
    ('chocolate mikado stick', 'Snacks'),
    ('chocolate truffle', 'Snacks'),
    ('chopped tomato', 'Vegetables'),
    ('chorizo', 'Meat'),
    ('christmas pudding', 'Pantry'),
    ('ciabatta', 'Bakery'),
    ('cider', 'Drinks'),
    ('cider vinegar', 'Drinks'),
    ('cinnamon', 'Pantry'),
    ('cinnamon stick', 'Pantry'),
    ('citrus candied peel', 'Pantry'),
    ('clarified butter', 'Dairy'),
    ('clear honey', 'Pantry'),
    ('clementine', 'Drinks'),
    ('clementine juice', 'Drinks'),
    ('clotted', 'Dairy'),
    ('clotted cream', 'Dairy'),
    ('cloudy apple juice', 'Fruit'),
    ('clove', 'Pantry'),
    ('coarse', 'Pantry'),
    ('coarse breadcrumb', 'Bakery'),
    ('coarse sea salt', 'Pantry'),
    ('cocktail cherry', 'Pantry'),
    ('cocktail sausage', 'Meat'),
    ('cocoa', 'Pantry'),
    ('cocoa powder', 'Pantry'),
    ('coconut', 'Fruit'),
    ('coconut butter', 'Dairy'),
    ('coconut cream', 'Dairy'),
    ('coconut flake', 'Fruit'),
    ('coconut milk', 'Dairy'),
    ('coconut rum', 'Fruit'),
    ('coconut shaving', 'Fruit'),
    ('coconut water', 'Fruit'),
    ('coconut yogurt', 'Dairy'),
    ('coffee', 'Drinks'),
    ('coffee essence', 'Drinks'),
    ('coffee granule', 'Drinks'),
    ('cointreau', 'Pantry'),
    ('cola', 'Pantry'),
    ('comté', 'Dairy'),
    ('concentrated chicken stock', 'Meat'),
    ('condensed milk', 'Dairy'),
    ('conference pear', 'Fruit'),
    ('cookie', 'Snacks'),
    ('cooking apple', 'Fruit'),
    ('cooking chorizo', 'Meat'),
    ('coriander', 'Vegetables'),
    ('coriander seed', 'Vegetables'),
    ('corn tortilla', 'Pantry'),
    ('corn tortilla chip', 'Snacks'),
    ('cornflour', 'Pantry'),
    ('cornichon', 'Pantry'),
    ('country', 'Pantry'),
    ('courgette', 'Vegetables'),
    ('couscous', 'Pantry'),
    ("cox's apple", 'Fruit'),
    ('crabmeat', 'Meat'),
    ('cracked black peppercorn', 'Vegetables'),
    ('cranberry', 'Fruit'),
    ('cranberry jelly', 'Fruit'),
    ('cranberry sauce', 'Fruit'),
    ('crayfishtail', 'Fish'),
    ('cream', 'Dairy'),
    ('cream cheese', 'Dairy'),
    ('creamed coconut', 'Dairy'),
    ('creamed horseradish', 'Dairy'),
    ('creamed horseradish sauce', 'Dairy'),
    ('creamor ice cream', 'Dairy'),
    ('crisp lettuce leaf', 'Vegetables'),
    ('croissant', 'Bakery'),
    ('crushed', 'Pantry'),
    ('crustless sliced white bread', 'Bakery'),
    ('crystallised angelica', 'Pantry'),
    ('crystallised fruit', 'Fruit'),
    ('crystallised ginger', 'Drinks'),
    ('crème de cacao', 'Pantry'),
    ('crème de cassis', 'Pantry'),
    ('crème fraîche', 'Dairy'),
    ('cucumber', 'Vegetables'),
    ('cumberland sausage', 'Meat'),
    ('cumin', 'Pantry'),
    ('cumin seed', 'Pantry'),
    ('curly lettuce', 'Vegetables'),
    ('currant', 'Fruit'),
    ('curry paste', 'Pantry'),
    ('curry powder', 'Pantry'),
    ('custard', 'Dairy'),
    ('dark chocolate', 'Snacks'),
    ('date', 'Fruit'),
    ('demerara sugar', 'Pantry'),
    ('demerara sugarto sprinkle', 'Pantry'),
    ('desiccated coconut', 'Fruit'),
    ('dessert apple', 'Fruit'),
    ('died fruit', 'Fruit'),
    ('digestive biscuit', 'Snacks'),
    ('dijon mustard', 'Pantry'),
    ('dill', 'Pantry'),
    ('disaronno originale liqueur disaronno', 'Drinks'),
    ('double cream', 'Dairy'),
    ('drained chickpea', 'Vegetables'),
    ('dried apricot', 'Fruit'),
    ('dried cranberries', 'Fruit'),
    ('dried fruit', 'Fruit'),
    ('dried raisin', 'Fruit'),
    ('drops almondextract', 'Snacks'),
    ('drops of peppermint essence', 'Vegetables'),
    ('dry cider', 'Drinks'),
    ('dry sherry', 'Pantry'),
    ('dry white wine', 'Drinks'),
    ('duck', 'Meat'),
    ('duck breast', 'Meat'),
    ('duck fat', 'Meat'),
    ('duck leg', 'Meat'),
    ('duck liver', 'Meat'),
    ('duck pâté', 'Meat'),
    ('dulce de leche', 'Pantry'),
    ('e black writing icing', 'Pantry'),
    ('each brazil nut', 'Snacks'),
    ('each good', 'Dairy'),
    ('each semi', 'Fruit'),
    ('easy', 'Pantry'),
    ('eating apple', 'Fruit'),
    ('edible food colouring', 'Pantry'),
    ('edible goldleaf', 'Vegetables'),
    ('egg', 'Dairy'),
    ('egg noodle', 'Dairy'),
    ('egg white', 'Dairy'),
    ('egg yolk', 'Dairy'),
    ('elderflower cordial', 'Pantry'),
    ('english mustard', 'Pantry'),
    ('english mustard powder', 'Pantry'),
    ('espresso', 'Drinks'),
    ('fast', 'Pantry'),
    ('fast action dried yeast', 'Pantry'),
    ('fast-action dried yeast', 'Pantry'),
    ('fat', 'Dairy'),
    ('fennel bulb', 'Pantry'),
    ('fennel seed', 'Pantry'),
    ('fenugreek seed', 'Pantry'),
    ('feta cheese', 'Dairy'),
    ('field mushroom', 'Vegetables'),
    ('fig', 'Fruit'),
    ('fig jam', 'Fruit'),
    ('filo pastry', 'Bakery'),
    ('fine', 'Drinks'),
    ('fine shred orange marmalade', 'Fruit'),
    ('finely grated vegetarian', 'Dairy'),
    ('finely snipped chive', 'Pantry'),
    ('finger', 'Vegetables'),
    ('fino sherry', 'Pantry'),
    ('firm', 'Fruit'),
    ('fish sauce', 'Fish'),
    ('fishfillet', 'Fish'),
    ('five spice', 'Pantry'),
    ('five spice powder', 'Pantry'),
    ('flaked almond', 'Snacks'),
    ('flaky sea salt', 'Pantry'),
    ('flat', 'Vegetables'),
    ('flat mushroom', 'Vegetables'),
    ('flat-leaf parsley', 'Vegetables'),
    ('flavourless oil', 'Pantry'),
    ('flour', 'Pantry'),
    ('fondant chocolate', 'Snacks'),
    ('fondant icing', 'Bakery'),
    ('fondant icing sugar', 'Pantry'),
    ('food colouring', 'Pantry'),
    ('food colouring gelof your choice', 'Pantry'),
    ('food colouring paste', 'Pantry'),
    ('food colouringpaste in various colour', 'Pantry'),
    ('free', 'Meat'),
    ('freeze', 'Fruit'),
    ('french brandy', 'Drinks'),
    ('freshly grated horseradish', 'Pantry'),
    ('fruit', 'Fruit'),
    ('fruit cake', 'Bakery'),
    ('fruit tea', 'Fruit'),
    ('fruity panettone', 'Fruit'),
    ('gammonjoint', 'Pantry'),
    ('gammonon the bone', 'Pantry'),
    ('garam masala', 'Pantry'),
    ('garlic', 'Vegetables'),
    ('garlic and herb cream cheese', 'Dairy'),
    ('garlic bulb', 'Vegetables'),
    ('garlic butter', 'Dairy'),
    ('garlic clove', 'Vegetables'),
    ('garlicbulb', 'Vegetables'),
    ('gelatine', 'Pantry'),
    ('gem lettuce', 'Vegetables'),
    ('giant chocolate button', 'Snacks'),
    ('gin', 'Drinks'),
    ('ginger', 'Drinks'),
    ('ginger beer', 'Drinks'),
    ('ginger nut', 'Drinks'),
    ('ginger preserve', 'Drinks'),
    ('ginger syrup', 'Drinks'),
    ('glace cherry', 'Pantry'),
    ('glass of red wine', 'Drinks'),
    ('gluten', 'Pantry'),
    ('gnocchi', 'Pantry'),
    ("goat's cheese", 'Dairy'),
    ('golden caster sugar', 'Pantry'),
    ('golden granulated sugar', 'Pantry'),
    ('golden marzipan', 'Snacks'),
    ('golden syrup', 'Pantry'),
    ('good', 'Dairy'),
    ('goose', 'Meat'),
    ('goose fat', 'Meat'),
    ('grand marnier', 'Pantry'),
    ('granny smith', 'Pantry'),
    ('granny smith apple', 'Fruit'),
    ('granny smiths apple', 'Fruit'),
    ('granulated sugar', 'Pantry'),
    ('grape', 'Fruit'),
    ('grape molasses', 'Fruit'),
    ('greek yoghurt', 'Dairy'),
    ('greek yogurt', 'Dairy'),
    ('green bean', 'Vegetables'),
    ('grenadine', 'Pantry'),
    ('grilled artichoke heart', 'Vegetables'),
    ('ground allspice', 'Pantry'),
    ('ground almond', 'Snacks'),
    ('ground arrowroot', 'Pantry'),
    ('ground black pepper', 'Vegetables'),
    ('ground chia seeds', 'Pantry'),
    ('ground cinnamon', 'Pantry'),
    ('ground clove', 'Pantry'),
    ('ground cloves', 'Pantry'),
    ('ground coriander', 'Vegetables'),
    ('ground cumin', 'Pantry'),
    ('ground ginger', 'Drinks'),
    ('ground mace', 'Pantry'),
    ('ground mixed spice', 'Pantry'),
    ('ground nutmeg', 'Pantry'),
    ('ground spice', 'Pantry'),
    ('ground white pepper', 'Vegetables'),
    ('gruyère', 'Dairy'),
    ('haddock', 'Fish'),
    ('halloumi cheese', 'Dairy'),
    ('ham', 'Meat'),
    ('hard', 'Dairy'),
    ('hard cheese', 'Dairy'),
    ('harissa', 'Pantry'),
    ('harissa paste', 'Pantry'),
    ('hazelnut', 'Snacks'),
    ('hazelnut oil', 'Snacks'),
    ('head garlic', 'Vegetables'),
    ('heaped tsp dijon mustard', 'Pantry'),
    ('heaped tsp mignonette pepper', 'Vegetables'),
    ('heather honey', 'Pantry'),
    ('herb', 'Vegetables'),
    ('herbssuch as bay', 'Vegetables'),
    ('high', 'Snacks'),
    ('hoisin sauce', 'Pantry'),
    ('honey', 'Pantry'),
    ('horlicks powder', 'Pantry'),
    ('horseradish', 'Pantry'),
    ('horseradish cream', 'Dairy'),
    ('horseradish sauce', 'Pantry'),
    ('hundreds and thousands', 'Pantry'),
    ('ice cream', 'Dairy'),
    ('iced water', 'Drinks'),
    ('icing sugar', 'Pantry'),
    ('instant coffee granule', 'Drinks'),
    ('irish whiskey', 'Drinks'),
    ('italian flatbread', 'Bakery'),
    ('italian sausage', 'Meat'),
    ('japanese rice vinegar', 'Pantry'),
    ('jerusalem artichoke', 'Vegetables'),
    ('joint middle', 'Meat'),
    ('jumbo chocolate button', 'Snacks'),
    ('juniper berry', 'Fruit'),
    ('just', 'Fruit'),
    ('kahlúa', 'Pantry'),
    ('kalamata', 'Pantry'),
    ('kale', 'Drinks'),
    ('king prawn', 'Fish'),
    ('kirsch', 'Pantry'),
    ('lamb', 'Meat'),
    ('lard', 'Pantry'),
    ('lardon', 'Meat'),
    ('leaf', 'Vegetables'),
    ('leaf gelatine', 'Vegetables'),
    ('lean back bacon', 'Meat'),
    ('leek', 'Vegetables'),
    ('leg of gammon', 'Pantry'),
    ('lemon', 'Fruit'),
    ('lemon curd', 'Fruit'),
    ('lemon juice', 'Fruit'),
    ('lemon thyme leaf', 'Fruit'),
    ('lemon wedge', 'Fruit'),
    ('lemongrass', 'Fruit'),
    ('lemonzest', 'Fruit'),
    ('lentil', 'Vegetables'),
    ('lime', 'Fruit'),
    ('lime juice', 'Fruit'),
    ('lime leaf', 'Fruit'),
    ('lime wedge', 'Fruit'),
    ('limoncello', 'Pantry'),
    ('liquid glucose', 'Pantry'),
    ('liquid molasses', 'Pantry'),
    ('loaf of walnut', 'Bakery'),
    ('lolly stick', 'Drinks'),
    ('macadamia nut', 'Pantry'),
    ('mace', 'Pantry'),
    ('mace blade', 'Pantry'),
    ('mackerel', 'Fish'),
    ('mackerel fillet', 'Fish'),
    ('madeira', 'Pantry'),
    ('madeira cake', 'Pantry'),
    ('madeiracake crumb', 'Drinks'),
    ('madras curry powder', 'Pantry'),
    ('maldon salt', 'Pantry'),
    ('maldon sea salt', 'Pantry'),
    ('malibu', 'Drinks'),
    ('malt', 'Pantry'),
    ('malt extract', 'Pantry'),
    ('malted milk biscuit', 'Dairy'),
    ('malteser', 'Pantry'),
    ('manchego', 'Dairy'),
    ('mango', 'Fruit'),
    ('mango & prawnskewer', 'Fish'),
    ('mango chutney', 'Fruit'),
    ('maple syrup', 'Pantry'),
    ('maraschino cherry', 'Fruit'),
    ('marmite', 'Pantry'),
    ('marrons glace', 'Snacks'),
    ('marsala', 'Pantry'),
    ('marshmallow', 'Pantry'),
    ('marzipan', 'Snacks'),
    ('mascarpone', 'Dairy'),
    ('mature cheddar', 'Dairy'),
    ('mayonnaise', 'Pantry'),
    ('medium sliced loaf of bread', 'Bakery'),
    ('medjool date', 'Fruit'),
    ('melba toast', 'Bakery'),
    ('membrillo', 'Pantry'),
    ('meringuenest', 'Pantry'),
    ('mild chilli powder', 'Vegetables'),
    ('mild curry powder', 'Pantry'),
    ('mild red chilli', 'Vegetables'),
    ('milk', 'Dairy'),
    ('milk chocolate', 'Dairy'),
    ('milk powder', 'Dairy'),
    ('mince pies', 'Meat'),
    ('mincemeat', 'Meat'),
    ('mini', 'Bakery'),
    ('mini chocolatebean', 'Vegetables'),
    ('mini meringue', 'Pantry'),
    ('mini poppadum', 'Bakery'),
    ('mini white chocolate button', 'Snacks'),
    ('mint', 'Pantry'),
    ('mint extract', 'Pantry'),
    ('miso paste', 'Pantry'),
    ('mix of cheesesyou have around', 'Dairy'),
    ('mixed berry', 'Fruit'),
    ('mixed dried fruit', 'Fruit'),
    ('mixed nut', 'Snacks'),
    ('mixture of raisin', 'Fruit'),
    ('molasses', 'Pantry'),
    ('molasses cane sugar', 'Pantry'),
    ('morello cherry jam', 'Fruit'),
    ('mouli', 'Vegetables'),
    ('mozzarella', 'Dairy'),
    ('muffin case', 'Bakery'),
    ('mulled wine', 'Drinks'),
    ('muscatel', 'Fruit'),
    ('mushroom', 'Vegetables'),
    ('mustard powder', 'Pantry'),
    ('mustard seed', 'Pantry'),
    ('naan bread', 'Bakery'),
    ('natural', 'Snacks'),
    ('natural yogurt', 'Dairy'),
    ('naturally smoked haddock', 'Fish'),
    ('nice baby gem lettuceleave', 'Vegetables'),
    ('nut', 'Pantry'),
    ('nutmeg', 'Pantry'),
    ('nutritional yeast', 'Pantry'),
    ('oil', 'Pantry'),
    ('olive', 'Pantry'),
    ('olive oil', 'Pantry'),
    ('onion', 'Vegetables'),
    ('onion squash', 'Dairy'),
    ('oon', 'Pantry'),
    ('orange', 'Fruit'),
    ('orange curaçao', 'Fruit'),
    ('orange flower water', 'Fruit'),
    ('orange fruit pastille', 'Fruit'),
    ('orange juice', 'Fruit'),
    ('orange liqueur', 'Fruit'),
    ('orange milk chocolate', 'Dairy'),
    ('orange syrup', 'Fruit'),
    ('orange twist', 'Fruit'),
    ('orange water', 'Fruit'),
    ('orange zest', 'Fruit'),
    ('oregano', 'Pantry'),
    ('oreo biscuit', 'Snacks'),
    ('orgeat', 'Snacks'),
    ('oyster', 'Fish'),
    ('oyster sauce', 'Fish'),
    ('paella rice', 'Pantry'),
    ('palm', 'Pantry'),
    ('pancetta', 'Meat'),
    ('papaya', 'Pantry'),
    ('paprika', 'Pantry'),
    ('pared zest', 'Fruit'),
    ('parma ham', 'Meat'),
    ('parmesan', 'Dairy'),
    ('parsley', 'Vegetables'),
    ('parsley leaf', 'Vegetables'),
    ('parsnip', 'Vegetables'),
    ('party sausage', 'Meat'),
    ('passata', 'Pantry'),
    ('pastashape', 'Pantry'),
    ('pea', 'Vegetables'),
    ('peanut', 'Fruit'),
    ('peanut butter', 'Dairy'),
    ('pear', 'Fruit'),
    ('pecan', 'Snacks'),
    ('pecan nut', 'Snacks'),
    ('pecannut', 'Snacks'),
    ('peel', 'Pantry'),
    ('pepper', 'Vegetables'),
    ('peppercorn', 'Vegetables'),
    ('peppermint candy cane', 'Vegetables'),
    ('peppermintextract', 'Vegetables'),
    ('peppersauce', 'Vegetables'),
    ('perry', 'Drinks'),
    ('persimmon', 'Pantry'),
    ('pesto', 'Pantry'),
    ('picked thyme leaf', 'Vegetables'),
    ("pimm's", 'Pantry'),
    ('pinch mixed spice', 'Pantry'),
    ('pinch of mustard powder', 'Pantry'),
    ('pine nut', 'Pantry'),
    ('pineapple', 'Fruit'),
    ('pineapple chunk', 'Fruit'),
    ('pineapple juice', 'Fruit'),
    ('ping', 'Pantry'),
    ('pink peppercorn', 'Vegetables'),
    ('pistachio', 'Snacks'),
    ('pistachio paste', 'Snacks'),
    ('pistachios', 'Snacks'),
    ('plain chocolate', 'Snacks'),
    ('plain dark chocolate', 'Snacks'),
    ('plain flour', 'Pantry'),
    ('plump duck breast', 'Meat'),
    ('plump red chilli', 'Fruit'),
    ('polenta', 'Pantry'),
    ('pomegranate', 'Pantry'),
    ('pomegranate juice', 'Drinks'),
    ('pomegranate molasses', 'Pantry'),
    ('pomegranate seed', 'Pantry'),
    ('poppy seed', 'Pantry'),
    ('porcini mushroom', 'Vegetables'),
    ('pork bellyslice', 'Meat'),
    ('pork fillet', 'Meat'),
    ('pork loin', 'Meat'),
    ('pork mince', 'Meat'),
    ('pork sausage', 'Meat'),
    ('porridge oat', 'Pantry'),
    ('port', 'Pantry'),
    ('portabellini mushroom', 'Vegetables'),
    ('potato', 'Vegetables'),
    ('prawn', 'Fish'),
    ('prawncocktail', 'Fish'),
    ('pre', 'Fish'),
    ('preserving sugar', 'Pantry'),
    ('pretzel', 'Snacks'),
    ('pretzelstick', 'Snacks'),
    ('prosciutto', 'Meat'),
    ('prosecco', 'Drinks'),
    ('prune', 'Fruit'),
    ('puff pastry', 'Bakery'),
    ('pumpkin seed', 'Vegetables'),
    ('puy lentil', 'Vegetables'),
    ('quantity soft royal icing', 'Pantry'),
    ('quick', 'Pantry'),
    ('quince', 'Fruit'),
    ('quince jelly', 'Fruit'),
    ('radicchio', 'Pantry'),
    ('raisin', 'Fruit'),
    ('rapeseed oil', 'Pantry'),
    ('ras el hanout', 'Pantry'),
    ('raspberry', 'Fruit'),
    ('raspberry jam', 'Fruit'),
    ('read', 'Fruit'),
    ('red', 'Fruit'),
    ('red chilli', 'Vegetables'),
    ('red food colouring', 'Pantry'),
    ('red onion', 'Vegetables'),
    ('red pepper', 'Vegetables'),
    ('red wine', 'Drinks'),
    ('redcurrant', 'Fruit'),
    ('redcurrant jelly', 'Fruit'),
    ('reduced', 'Dairy'),
    ('regal', 'Bakery'),
    ('rib of beef', 'Meat'),
    ('rice', 'Pantry'),
    ('rice vinegar', 'Pantry'),
    ('ricotta', 'Dairy'),
    ('rindless streaky bacon', 'Meat'),
    ('rings of dried', 'Fruit'),
    ('risotto rice', 'Pantry'),
    ('roast', 'Vegetables'),
    ('roast turnip', 'Vegetables'),
    ('roasted rhubarb', 'Pantry'),
    ('roasted salted peanut', 'Vegetables'),
    ('roasted vegetable', 'Vegetables'),
    ('rock salt', 'Pantry'),
    ('rocket leaf', 'Pantry'),
    ('rocket leaves', 'Vegetables'),
    ('rolled', 'Meat'),
    ('rolled oat', 'Bakery'),
    ('romaine lettuce', 'Vegetables'),
    ('root ginger', 'Drinks'),
    ('rose harissa', 'Pantry'),
    ('rosemary', 'Vegetables'),
    ('rosewater', 'Drinks'),
    ('roughly crushed white peppercorn', 'Vegetables'),
    ('royal icing mix', 'Pantry'),
    ('royal icing sugar', 'Pantry'),
    ('ruby port', 'Pantry'),
    ('rum', 'Drinks'),
    ('runny honey', 'Pantry'),
    ('rye bread', 'Bakery'),
    ('rye breadloaf', 'Bakery'),
    ('rye cracker', 'Bakery'),
    ('saba', 'Fruit'),
    ('saffron', 'Pantry'),
    ('sage', 'Vegetables'),
    ('salad', 'Pantry'),
    ('salad dressing', 'Pantry'),
    ('salad leaf', 'Pantry'),
    ('salmon', 'Fish'),
    ('salmon fillet', 'Fish'),
    ('salmon slice', 'Fish'),
    ('salmontrimming', 'Fish'),
    ('salt', 'Pantry'),
    ('salted butter', 'Dairy'),
    ('satsuma', 'Drinks'),
    ('sausage', 'Meat'),
    ('sausagemeat', 'Meat'),
    ('sausages', 'Meat'),
    ('savoy', 'Vegetables'),
    ('savoy cabbage', 'Vegetables'),
    ('scallop', 'Fish'),
    ('sea bass', 'Fish'),
    ('sea salt', 'Pantry'),
    ('sea salt flake', 'Pantry'),
    ('sea saltflake', 'Pantry'),
    ('seafood prawn', 'Fish'),
    ('seedless clementine', 'Pantry'),
    ('self', 'Fruit'),
    ('semi', 'Dairy'),
    ('semolina', 'Pantry'),
    ('serrano ham', 'Meat'),
    ('sesame oil', 'Pantry'),
    ('sesame seed', 'Pantry'),
    ('seville orange marmalade', 'Fruit'),
    ('shakes tabasco', 'Pantry'),
    ('shallot', 'Vegetables'),
    ('shaohsing wine', 'Drinks'),
    ('sherry', 'Drinks'),
    ('sherry vinegar', 'Pantry'),
    ('shiitake mushroom', 'Vegetables'),
    ('shortbread dough', 'Bakery'),
    ('shortcrust pastry', 'Bakery'),
    ('shot of espressocoffee', 'Drinks'),
    ('shoulder', 'Meat'),
    ('shredded', 'Meat'),
    ('shredless marmalade', 'Pantry'),
    ('side of salmon', 'Fish'),
    ('side of very fresh salmon', 'Fish'),
    ('sifted icing sugar', 'Pantry'),
    ('silken tofu', 'Pantry'),
    ('silver ball', 'Pantry'),
    ('single cream', 'Dairy'),
    ('skin', 'Pantry'),
    ('skinless', 'Fish'),
    ('slightly salted butter', 'Dairy'),
    ('sloe gin', 'Drinks'),
    ('smarty', 'Snacks'),
    ('smoked', 'Meat'),
    ('smoked mackerel', 'Fish'),
    ('soft black liquorice', 'Drinks'),
    ('soft brown sugar', 'Pantry'),
    ('soft butter', 'Dairy'),
    ('soft cheese', 'Dairy'),
    ('soft dried apricot', 'Fruit'),
    ('soft light brown sugar', 'Pantry'),
    ('soft light muscovado sugar', 'Pantry'),
    ('sour cherry', 'Pantry'),
    ('sourdough', 'Pantry'),
    ('sourdough bread', 'Bakery'),
    ('soured cream', 'Dairy'),
    ('soy sauce', 'Pantry'),
    ('soya cream', 'Dairy'),
    ('spice', 'Pantry'),
    ('spiced rum', 'Drinks'),
    ('spinach', 'Vegetables'),
    ('splash vinegar', 'Pantry'),
    ('sponge cake', 'Pantry'),
    ('spray oil', 'Pantry'),
    ('spring green', 'Pantry'),
    ('spring onion', 'Bakery'),
    ('sprinkle', 'Pantry'),
    ('sprinkling caster sugar', 'Pantry'),
    ('sprout', 'Vegetables'),
    ('square butter muslin', 'Dairy'),
    ('square suit', 'Pantry'),
    ('squash', 'Vegetables'),
    ('squeeze of lime juice', 'Fruit'),
    ('stale french stick', 'Drinks'),
    ('star anise', 'Pantry'),
    ('stem ginger', 'Drinks'),
    ('stem ginger syrup', 'Drinks'),
    ('stem gingerin syrup', 'Drinks'),
    ('stilton', 'Drinks'),
    ('streaky bacon', 'Meat'),
    ('string', 'Drinks'),
    ('strong', 'Meat'),
    ('strong mint', 'Pantry'),
    ('strong plain flour', 'Pantry'),
    ('strong white bread flour', 'Bakery'),
    ('strong white flour', 'Pantry'),
    ('stuffing', 'Pantry'),
    ('suet', 'Pantry'),
    ('sugar', 'Pantry'),
    ('sugar cube', 'Pantry'),
    ('sugar lump', 'Pantry'),
    ('sultana', 'Fruit'),
    ('summer fruit', 'Fruit'),
    ('sundried tomato', 'Vegetables'),
    ('sunflower oil', 'Pantry'),
    ('sunflower seeds', 'Pantry'),
    ('swede', 'Vegetables'),
    ('sweet', 'Drinks'),
    ('sweet cherriesdefrosted', 'Frozen'),
    ('sweet chilli sauce', 'Vegetables'),
    ('sweet potato', 'Vegetables'),
    ('sweet smoked paprika', 'Pantry'),
    ('sweet white wine', 'Fruit'),
    ('sweetcorn', 'Frozen'),
    ('sweets', 'Fruit'),
    ('tabasco', 'Pantry'),
    ('tamari', 'Pantry'),
    ('tamari soy sauce', 'Pantry'),
    ('tangerine', 'Pantry'),
    ('tarragon', 'Pantry'),
    ('teriyaki sauce', 'Pantry'),
    ('thai chilli', 'Vegetables'),
    ('thai fish sauce', 'Fish'),
    ('thai red curry paste', 'Pantry'),
    ('the turkeyneck', 'Meat'),
    ('thumb', 'Drinks'),
    ('thyme', 'Vegetables'),
    ('thyme leaf', 'Vegetables'),
    ('tia maria', 'Drinks'),
    ('tied gammonjoint', 'Pantry'),
    ('tiger prawn', 'Fish'),
    ('toffee sauce', 'Pantry'),
    ('tomato', 'Vegetables'),
    ('tomato juice', 'Vegetables'),
    ('tomato ketchup', 'Vegetables'),
    ('tomato purée', 'Vegetables'),
    ('tomatoeson the vine', 'Vegetables'),
    ('tonic water', 'Drinks'),
    ('top', 'Dairy'),
    ('toppings of your choice', 'Pantry'),
    ('tortilla wraps', 'Pantry'),
    ('treacle', 'Pantry'),
    ('trimming', 'Bakery'),
    ('trinket', 'Vegetables'),
    ('triple sec', 'Pantry'),
    ('tropical dried fruit medley', 'Fruit'),
    ('truffle', 'Pantry'),
    ('truffle oil', 'Pantry'),
    ('truffleshaving', 'Pantry'),
    ('tuna', 'Fish'),
    ('turkey', 'Meat'),
    ('turkey breast', 'Meat'),
    ('turkey breast fillet', 'Meat'),
    ('turkey breast steak', 'Meat'),
    ('turkey crown', 'Meat'),
    ('turkey mince', 'Meat'),
    ('turkeyneck', 'Meat'),
    ('turkish delight', 'Drinks'),
    ('turmeric', 'Pantry'),
    ('turnip', 'Vegetables'),
    ('turquoise food colouring', 'Pantry'),
    ('tzatziki', 'Pantry'),
    ('uette', 'Pantry'),
    ('uncooked ham', 'Meat'),
    ('unpeeled salad', 'Vegetables'),
    ("unrefined billington's icing sugar", 'Drinks'),
    ('unsalted butter', 'Dairy'),
    ('unscented coconut oil', 'Fruit'),
    ('unsmoked boneless gammon', 'Pantry'),
    ('unsmoked boneless gammonjoint', 'Pantry'),
    ('unsmoked leg of gammon', 'Pantry'),
    ('vanilla', 'Pantry'),
    ('vanilla bean paste', 'Vegetables'),
    ('vanilla essence', 'Pantry'),
    ('vanilla extract', 'Pantry'),
    ('vanilla ice cream', 'Dairy'),
    ('vanilla pod', 'Pantry'),
    ('veal stock', 'Meat'),
    ('veg stock', 'Drinks'),
    ('vegan white wine vinegar', 'Drinks'),
    ('vegetable', 'Vegetables'),
    ('vegetable bouillon powder', 'Drinks'),
    ('vegetable oil', 'Pantry'),
    ('vegetable stock', 'Drinks'),
    ('vegetable stock cube', 'Drinks'),
    ('vegetable stockcube', 'Drinks'),
    ('vegetarian cheddar', 'Dairy'),
    ('venison loin', 'Meat'),
    ('venison sausage', 'Meat'),
    ('vermouth', 'Drinks'),
    ('vinaigrette', 'Pantry'),
    ('vine', 'Vegetables'),
    ('vine tomato', 'Vegetables'),
    ('virgin olive oil', 'Drinks'),
    ('vodka', 'Drinks'),
    ('walnut', 'Snacks'),
    ('walnut oil', 'Snacks'),
    ('walnut whip', 'Snacks'),
    ('water', 'Drinks'),
    ('watercress', 'Vegetables'),
    ('wedge of camembert', 'Pantry'),
    ('whisky', 'Drinks'),
    ('white bread', 'Bakery'),
    ('white chicory', 'Pantry'),
    ('white chocolate', 'Snacks'),
    ('white chocolate button', 'Snacks'),
    ('white wine', 'Drinks'),
    ('wholegrain mustard', 'Pantry'),
    ('wholemeal flour', 'Pantry'),
    ('wholemeal plain flour', 'Pantry'),
    ('wholemeal vegan breadcrumb', 'Bakery'),
    ('wild mushroom', 'Vegetables'),
    ('wild rocket', 'Pantry'),
    ('williams pear', 'Fruit'),
    ('wine', 'Drinks'),
    ('wine vinegar', 'Drinks'),
    ('winter salad leaf', 'Pantry'),
    ('worcestershire sauce', 'Pantry'),
    ('writing icing', 'Pantry'),
    ('yeast', 'Pantry'),
    ('yogurt', 'Dairy'),
    ('young spinachleave', 'Vegetables'),
    ("za'atar", 'Pantry'),
    ]

    category_cache = {
        category.name: category
        for category in Category.objects.all()
    }

    for ingredient_name, category_name in ingredients:
        category = category_cache.get(category_name)
        Ingredient.objects.get_or_create(
            name=ingredient_name,
            defaults={'category': category}
        )


def unload_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('app', 'Ingredient')

    ingredient_names = [
    ('after eight', 'Pantry'),
    ('all-butter puff pastry', 'Dairy'),
    ('allspice', 'Pantry'),
    ('allspice berry', 'Fruit'),
    ('almond', 'Snacks'),
    ('almond extract', 'Snacks'),
    ('almond milk', 'Dairy'),
    ('almond milk chocolate', 'Dairy'),
    ('amaretti biscuit', 'Snacks'),
    ('amaretto', 'Pantry'),
    ('amaretto liqueur', 'Drinks'),
    ('anchovy', 'Fish'),
    ('angostura bitter', 'Pantry'),
    ('apple', 'Fruit'),
    ('apple cider vinegar', 'Fruit'),
    ('apple juice', 'Fruit'),
    ('apricot', 'Fruit'),
    ('apricot jam', 'Fruit'),
    ('arrowroot', 'Pantry'),
    ('assorted food colouring', 'Pantry'),
    ('aubergine', 'Drinks'),
    ('avocado', 'Fruit'),
    ('baby beetroot', 'Vegetables'),
    ('baby leek', 'Vegetables'),
    ('baby onion', 'Vegetables'),
    ('baby spinach', 'Vegetables'),
    ('baby turnip', 'Vegetables'),
    ('back bacon', 'Meat'),
    ('bacon', 'Meat'),
    ('bacon lardon', 'Meat'),
    ('baconlardon', 'Meat'),
    ('baileyscream liqueur', 'Dairy'),
    ('baking powder', 'Pantry'),
    ('balsamic vinegar', 'Pantry'),
    ('banana', 'Fruit'),
    ('banana shallot', 'Fruit'),
    ('basil', 'Vegetables'),
    ('basmati rice', 'Pantry'),
    ('basmati wild ricemix', 'Pantry'),
    ('bavarian smoked cheese', 'Dairy'),
    ('bay leaf', 'Vegetables'),
    ('beansprout', 'Vegetables'),
    ('beef fillet', 'Meat'),
    ('beef stock', 'Meat'),
    ('beef stock cube', 'Meat'),
    ('beef suet', 'Meat'),
    ('beetroot', 'Vegetables'),
    ('berries', 'Fruit'),
    ('bicarbonate of soda', 'Pantry'),
    ("bird's custard powder", 'Dairy'),
    ("bird's-eye chilli", 'Vegetables'),
    ('black fondant', 'Pantry'),
    ('black mustard seed', 'Pantry'),
    ('black olive', 'Pantry'),
    ('black pepper', 'Vegetables'),
    ('black peppercorn', 'Vegetables'),
    ('black pudding', 'Meat'),
    ('black treacle', 'Pantry'),
    ('black writing icing', 'Pantry'),
    ('blackberry', 'Fruit'),
    ('blade mace', 'Pantry'),
    ('blanched almond', 'Snacks'),
    ('blanched hazelnut', 'Snacks'),
    ('blanched whole almond', 'Snacks'),
    ('blood orange', 'Fruit'),
    ('blue cheese', 'Dairy'),
    ('blue food colouringpaste', 'Pantry'),
    ('blueberry conserve', 'Fruit'),
    ('boiling water', 'Drinks'),
    ('bok choi', 'Pantry'),
    ('bouquet garni', 'Vegetables'),
    ('bourbon', 'Pantry'),
    ('boursin cheese', 'Dairy'),
    ('bovril', 'Pantry'),
    ('bramley apple', 'Fruit'),
    ('bramley apple sauce', 'Fruit'),
    ('brandy', 'Drinks'),
    ('bread mix', 'Bakery'),
    ('breadcrumb', 'Bakery'),
    ('brie', 'Pantry'),
    ('brioche roll', 'Bakery'),
    ('broad bean', 'Vegetables'),
    ('brown bread', 'Bakery'),
    ('brown lentil', 'Vegetables'),
    ('brown sugar', 'Pantry'),
    ('brussels sprout', 'Vegetables'),
    ('buckwheat flour', 'Pantry'),
    ('burger bun', 'Bakery'),
    ('butter', 'Dairy'),
    ('buttermilk', 'Dairy'),
    ('butternut squash', 'Dairy'),
    ('button mushroom', 'Vegetables'),
    ('cabbage', 'Vegetables'),
    ('caerphilly cheese', 'Dairy'),
    ('calvado', 'Drinks'),
    ('camembert', 'Pantry'),
    ('canapé blinis', 'Pantry'),
    ('caper', 'Pantry'),
    ('caramel', 'Dairy'),
    ('caraway seed', 'Pantry'),
    ('cardamom pod', 'Pantry'),
    ('carrot', 'Vegetables'),
    ('cashew nut', 'Snacks'),
    ('cassis', 'Pantry'),
    ('caster sugar', 'Pantry'),
    ('cauliflower', 'Vegetables'),
    ('caviarjacket', 'Pantry'),
    ('cayenne pepper', 'Vegetables'),
    ('celeriac', 'Pantry'),
    ('celery', 'Vegetables'),
    ('celery salt', 'Vegetables'),
    ('chamomile teabag', 'Meat'),
    ('champagne', 'Meat'),
    ('chantenay carrot', 'Vegetables'),
    ('charentais melon', 'Fruit'),
    ('cheddar', 'Dairy'),
    ('cheese', 'Dairy'),
    ('cherries', 'Fruit'),
    ('cherry', 'Fruit'),
    ('cherry brandy', 'Fruit'),
    ('cherry tomato', 'Fruit'),
    ('chervil', 'Pantry'),
    ('chestnut', 'Snacks'),
    ('chestnut mushroom', 'Vegetables'),
    ('chicken', 'Meat'),
    ('chicken breast', 'Meat'),
    ('chicken stock', 'Meat'),
    ('chicken stock cube', 'Meat'),
    ('chicken thighson the bone', 'Meat'),
    ('chicken wing', 'Meat'),
    ('chickpea', 'Vegetables'),
    ('chicory', 'Pantry'),
    ('chilled champagne', 'Meat'),
    ('chilli', 'Vegetables'),
    ('chilli flake', 'Vegetables'),
    ('chilli sauce', 'Vegetables'),
    ('chinese five', 'Pantry'),
    ('chinese five spice', 'Pantry'),
    ('chipolatasausage', 'Meat'),
    ('chive', 'Pantry'),
    ('chocolate', 'Snacks'),
    ('chocolate button', 'Snacks'),
    ('chocolate chip', 'Snacks'),
    ('chocolate digestive biscuit', 'Snacks'),
    ('chocolate ice cream', 'Dairy'),
    ('chocolate mikado stick', 'Snacks'),
    ('chocolate truffle', 'Snacks'),
    ('chopped tomato', 'Vegetables'),
    ('chorizo', 'Meat'),
    ('christmas pudding', 'Pantry'),
    ('ciabatta', 'Bakery'),
    ('cider', 'Drinks'),
    ('cider vinegar', 'Drinks'),
    ('cinnamon', 'Pantry'),
    ('cinnamon stick', 'Pantry'),
    ('citrus candied peel', 'Pantry'),
    ('clarified butter', 'Dairy'),
    ('clear honey', 'Pantry'),
    ('clementine', 'Drinks'),
    ('clementine juice', 'Drinks'),
    ('clotted', 'Dairy'),
    ('clotted cream', 'Dairy'),
    ('cloudy apple juice', 'Fruit'),
    ('clove', 'Pantry'),
    ('coarse', 'Pantry'),
    ('coarse breadcrumb', 'Bakery'),
    ('coarse sea salt', 'Pantry'),
    ('cocktail cherry', 'Pantry'),
    ('cocktail sausage', 'Meat'),
    ('cocoa', 'Pantry'),
    ('cocoa powder', 'Pantry'),
    ('coconut', 'Fruit'),
    ('coconut butter', 'Dairy'),
    ('coconut cream', 'Dairy'),
    ('coconut flake', 'Fruit'),
    ('coconut milk', 'Dairy'),
    ('coconut rum', 'Fruit'),
    ('coconut shaving', 'Fruit'),
    ('coconut water', 'Fruit'),
    ('coconut yogurt', 'Dairy'),
    ('coffee', 'Drinks'),
    ('coffee essence', 'Drinks'),
    ('coffee granule', 'Drinks'),
    ('cointreau', 'Pantry'),
    ('cola', 'Pantry'),
    ('comté', 'Dairy'),
    ('concentrated chicken stock', 'Meat'),
    ('condensed milk', 'Dairy'),
    ('conference pear', 'Fruit'),
    ('cookie', 'Snacks'),
    ('cooking apple', 'Fruit'),
    ('cooking chorizo', 'Meat'),
    ('coriander', 'Vegetables'),
    ('coriander seed', 'Vegetables'),
    ('corn tortilla', 'Pantry'),
    ('corn tortilla chip', 'Snacks'),
    ('cornflour', 'Pantry'),
    ('cornichon', 'Pantry'),
    ('country', 'Pantry'),
    ('courgette', 'Vegetables'),
    ('couscous', 'Pantry'),
    ("cox's apple", 'Fruit'),
    ('crabmeat', 'Meat'),
    ('cracked black peppercorn', 'Vegetables'),
    ('cranberry', 'Fruit'),
    ('cranberry jelly', 'Fruit'),
    ('cranberry sauce', 'Fruit'),
    ('crayfishtail', 'Fish'),
    ('cream', 'Dairy'),
    ('cream cheese', 'Dairy'),
    ('creamed coconut', 'Dairy'),
    ('creamed horseradish', 'Dairy'),
    ('creamed horseradish sauce', 'Dairy'),
    ('creamor ice cream', 'Dairy'),
    ('crisp lettuce leaf', 'Vegetables'),
    ('croissant', 'Bakery'),
    ('crushed', 'Pantry'),
    ('crustless sliced white bread', 'Bakery'),
    ('crystallised angelica', 'Pantry'),
    ('crystallised fruit', 'Fruit'),
    ('crystallised ginger', 'Drinks'),
    ('crème de cacao', 'Pantry'),
    ('crème de cassis', 'Pantry'),
    ('crème fraîche', 'Dairy'),
    ('cucumber', 'Vegetables'),
    ('cumberland sausage', 'Meat'),
    ('cumin', 'Pantry'),
    ('cumin seed', 'Pantry'),
    ('curly lettuce', 'Vegetables'),
    ('currant', 'Fruit'),
    ('curry paste', 'Pantry'),
    ('curry powder', 'Pantry'),
    ('custard', 'Dairy'),
    ('dark chocolate', 'Snacks'),
    ('date', 'Fruit'),
    ('demerara sugar', 'Pantry'),
    ('demerara sugarto sprinkle', 'Pantry'),
    ('desiccated coconut', 'Fruit'),
    ('dessert apple', 'Fruit'),
    ('died fruit', 'Fruit'),
    ('digestive biscuit', 'Snacks'),
    ('dijon mustard', 'Pantry'),
    ('dill', 'Pantry'),
    ('disaronno originale liqueur disaronno', 'Drinks'),
    ('double cream', 'Dairy'),
    ('drained chickpea', 'Vegetables'),
    ('dried apricot', 'Fruit'),
    ('dried cranberries', 'Fruit'),
    ('dried fruit', 'Fruit'),
    ('dried raisin', 'Fruit'),
    ('drops almondextract', 'Snacks'),
    ('drops of peppermint essence', 'Vegetables'),
    ('dry cider', 'Drinks'),
    ('dry sherry', 'Pantry'),
    ('dry white wine', 'Drinks'),
    ('duck', 'Meat'),
    ('duck breast', 'Meat'),
    ('duck fat', 'Meat'),
    ('duck leg', 'Meat'),
    ('duck liver', 'Meat'),
    ('duck pâté', 'Meat'),
    ('dulce de leche', 'Pantry'),
    ('e black writing icing', 'Pantry'),
    ('each brazil nut', 'Snacks'),
    ('each good', 'Dairy'),
    ('each semi', 'Fruit'),
    ('easy', 'Pantry'),
    ('eating apple', 'Fruit'),
    ('edible food colouring', 'Pantry'),
    ('edible goldleaf', 'Vegetables'),
    ('egg', 'Dairy'),
    ('egg noodle', 'Dairy'),
    ('egg white', 'Dairy'),
    ('egg yolk', 'Dairy'),
    ('elderflower cordial', 'Pantry'),
    ('english mustard', 'Pantry'),
    ('english mustard powder', 'Pantry'),
    ('espresso', 'Drinks'),
    ('fast', 'Pantry'),
    ('fast action dried yeast', 'Pantry'),
    ('fast-action dried yeast', 'Pantry'),
    ('fat', 'Dairy'),
    ('fennel bulb', 'Pantry'),
    ('fennel seed', 'Pantry'),
    ('fenugreek seed', 'Pantry'),
    ('feta cheese', 'Dairy'),
    ('field mushroom', 'Vegetables'),
    ('fig', 'Fruit'),
    ('fig jam', 'Fruit'),
    ('filo pastry', 'Bakery'),
    ('fine', 'Drinks'),
    ('fine shred orange marmalade', 'Fruit'),
    ('finely grated vegetarian', 'Dairy'),
    ('finely snipped chive', 'Pantry'),
    ('finger', 'Vegetables'),
    ('fino sherry', 'Pantry'),
    ('firm', 'Fruit'),
    ('fish sauce', 'Fish'),
    ('fishfillet', 'Fish'),
    ('five spice', 'Pantry'),
    ('five spice powder', 'Pantry'),
    ('flaked almond', 'Snacks'),
    ('flaky sea salt', 'Pantry'),
    ('flat', 'Vegetables'),
    ('flat mushroom', 'Vegetables'),
    ('flat-leaf parsley', 'Vegetables'),
    ('flavourless oil', 'Pantry'),
    ('flour', 'Pantry'),
    ('fondant chocolate', 'Snacks'),
    ('fondant icing', 'Bakery'),
    ('fondant icing sugar', 'Pantry'),
    ('food colouring', 'Pantry'),
    ('food colouring gelof your choice', 'Pantry'),
    ('food colouring paste', 'Pantry'),
    ('food colouringpaste in various colour', 'Pantry'),
    ('free', 'Meat'),
    ('freeze', 'Fruit'),
    ('french brandy', 'Drinks'),
    ('freshly grated horseradish', 'Pantry'),
    ('fruit', 'Fruit'),
    ('fruit cake', 'Bakery'),
    ('fruit tea', 'Fruit'),
    ('fruity panettone', 'Fruit'),
    ('gammonjoint', 'Pantry'),
    ('gammonon the bone', 'Pantry'),
    ('garam masala', 'Pantry'),
    ('garlic', 'Vegetables'),
    ('garlic and herb cream cheese', 'Dairy'),
    ('garlic bulb', 'Vegetables'),
    ('garlic butter', 'Dairy'),
    ('garlic clove', 'Vegetables'),
    ('garlicbulb', 'Vegetables'),
    ('gelatine', 'Pantry'),
    ('gem lettuce', 'Vegetables'),
    ('giant chocolate button', 'Snacks'),
    ('gin', 'Drinks'),
    ('ginger', 'Drinks'),
    ('ginger beer', 'Drinks'),
    ('ginger nut', 'Drinks'),
    ('ginger preserve', 'Drinks'),
    ('ginger syrup', 'Drinks'),
    ('glace cherry', 'Pantry'),
    ('glass of red wine', 'Drinks'),
    ('gluten', 'Pantry'),
    ('gnocchi', 'Pantry'),
    ("goat's cheese", 'Dairy'),
    ('golden caster sugar', 'Pantry'),
    ('golden granulated sugar', 'Pantry'),
    ('golden marzipan', 'Snacks'),
    ('golden syrup', 'Pantry'),
    ('good', 'Dairy'),
    ('goose', 'Meat'),
    ('goose fat', 'Meat'),
    ('grand marnier', 'Pantry'),
    ('granny smith', 'Pantry'),
    ('granny smith apple', 'Fruit'),
    ('granny smiths apple', 'Fruit'),
    ('granulated sugar', 'Pantry'),
    ('grape', 'Fruit'),
    ('grape molasses', 'Fruit'),
    ('greek yoghurt', 'Dairy'),
    ('greek yogurt', 'Dairy'),
    ('green bean', 'Vegetables'),
    ('grenadine', 'Pantry'),
    ('grilled artichoke heart', 'Vegetables'),
    ('ground allspice', 'Pantry'),
    ('ground almond', 'Snacks'),
    ('ground arrowroot', 'Pantry'),
    ('ground black pepper', 'Vegetables'),
    ('ground chia seeds', 'Pantry'),
    ('ground cinnamon', 'Pantry'),
    ('ground clove', 'Pantry'),
    ('ground cloves', 'Pantry'),
    ('ground coriander', 'Vegetables'),
    ('ground cumin', 'Pantry'),
    ('ground ginger', 'Drinks'),
    ('ground mace', 'Pantry'),
    ('ground mixed spice', 'Pantry'),
    ('ground nutmeg', 'Pantry'),
    ('ground spice', 'Pantry'),
    ('ground white pepper', 'Vegetables'),
    ('gruyère', 'Dairy'),
    ('haddock', 'Fish'),
    ('halloumi cheese', 'Dairy'),
    ('ham', 'Meat'),
    ('hard', 'Dairy'),
    ('hard cheese', 'Dairy'),
    ('harissa', 'Pantry'),
    ('harissa paste', 'Pantry'),
    ('hazelnut', 'Snacks'),
    ('hazelnut oil', 'Snacks'),
    ('head garlic', 'Vegetables'),
    ('heaped tsp dijon mustard', 'Pantry'),
    ('heaped tsp mignonette pepper', 'Vegetables'),
    ('heather honey', 'Pantry'),
    ('herb', 'Vegetables'),
    ('herbssuch as bay', 'Vegetables'),
    ('high', 'Snacks'),
    ('hoisin sauce', 'Pantry'),
    ('honey', 'Pantry'),
    ('horlicks powder', 'Pantry'),
    ('horseradish', 'Pantry'),
    ('horseradish cream', 'Dairy'),
    ('horseradish sauce', 'Pantry'),
    ('hundreds and thousands', 'Pantry'),
    ('ice cream', 'Dairy'),
    ('iced water', 'Drinks'),
    ('icing sugar', 'Pantry'),
    ('instant coffee granule', 'Drinks'),
    ('irish whiskey', 'Drinks'),
    ('italian flatbread', 'Bakery'),
    ('italian sausage', 'Meat'),
    ('japanese rice vinegar', 'Pantry'),
    ('jerusalem artichoke', 'Vegetables'),
    ('joint middle', 'Meat'),
    ('jumbo chocolate button', 'Snacks'),
    ('juniper berry', 'Fruit'),
    ('just', 'Fruit'),
    ('kahlúa', 'Pantry'),
    ('kalamata', 'Pantry'),
    ('kale', 'Drinks'),
    ('king prawn', 'Fish'),
    ('kirsch', 'Pantry'),
    ('lamb', 'Meat'),
    ('lard', 'Pantry'),
    ('lardon', 'Meat'),
    ('leaf', 'Vegetables'),
    ('leaf gelatine', 'Vegetables'),
    ('lean back bacon', 'Meat'),
    ('leek', 'Vegetables'),
    ('leg of gammon', 'Pantry'),
    ('lemon', 'Fruit'),
    ('lemon curd', 'Fruit'),
    ('lemon juice', 'Fruit'),
    ('lemon thyme leaf', 'Fruit'),
    ('lemon wedge', 'Fruit'),
    ('lemongrass', 'Fruit'),
    ('lemonzest', 'Fruit'),
    ('lentil', 'Vegetables'),
    ('lime', 'Fruit'),
    ('lime juice', 'Fruit'),
    ('lime leaf', 'Fruit'),
    ('lime wedge', 'Fruit'),
    ('limoncello', 'Pantry'),
    ('liquid glucose', 'Pantry'),
    ('liquid molasses', 'Pantry'),
    ('loaf of walnut', 'Bakery'),
    ('lolly stick', 'Drinks'),
    ('macadamia nut', 'Pantry'),
    ('mace', 'Pantry'),
    ('mace blade', 'Pantry'),
    ('mackerel', 'Fish'),
    ('mackerel fillet', 'Fish'),
    ('madeira', 'Pantry'),
    ('madeira cake', 'Pantry'),
    ('madeiracake crumb', 'Drinks'),
    ('madras curry powder', 'Pantry'),
    ('maldon salt', 'Pantry'),
    ('maldon sea salt', 'Pantry'),
    ('malibu', 'Drinks'),
    ('malt', 'Pantry'),
    ('malt extract', 'Pantry'),
    ('malted milk biscuit', 'Dairy'),
    ('malteser', 'Pantry'),
    ('manchego', 'Dairy'),
    ('mango', 'Fruit'),
    ('mango & prawnskewer', 'Fish'),
    ('mango chutney', 'Fruit'),
    ('maple syrup', 'Pantry'),
    ('maraschino cherry', 'Fruit'),
    ('marmite', 'Pantry'),
    ('marrons glace', 'Snacks'),
    ('marsala', 'Pantry'),
    ('marshmallow', 'Pantry'),
    ('marzipan', 'Snacks'),
    ('mascarpone', 'Dairy'),
    ('mature cheddar', 'Dairy'),
    ('mayonnaise', 'Pantry'),
    ('medium sliced loaf of bread', 'Bakery'),
    ('medjool date', 'Fruit'),
    ('melba toast', 'Bakery'),
    ('membrillo', 'Pantry'),
    ('meringuenest', 'Pantry'),
    ('mild chilli powder', 'Vegetables'),
    ('mild curry powder', 'Pantry'),
    ('mild red chilli', 'Vegetables'),
    ('milk', 'Dairy'),
    ('milk chocolate', 'Dairy'),
    ('milk powder', 'Dairy'),
    ('mince pies', 'Meat'),
    ('mincemeat', 'Meat'),
    ('mini', 'Bakery'),
    ('mini chocolatebean', 'Vegetables'),
    ('mini meringue', 'Pantry'),
    ('mini poppadum', 'Bakery'),
    ('mini white chocolate button', 'Snacks'),
    ('mint', 'Pantry'),
    ('mint extract', 'Pantry'),
    ('miso paste', 'Pantry'),
    ('mix of cheesesyou have around', 'Dairy'),
    ('mixed berry', 'Fruit'),
    ('mixed dried fruit', 'Fruit'),
    ('mixed nut', 'Snacks'),
    ('mixture of raisin', 'Fruit'),
    ('molasses', 'Pantry'),
    ('molasses cane sugar', 'Pantry'),
    ('morello cherry jam', 'Fruit'),
    ('mouli', 'Vegetables'),
    ('mozzarella', 'Dairy'),
    ('muffin case', 'Bakery'),
    ('mulled wine', 'Drinks'),
    ('muscatel', 'Fruit'),
    ('mushroom', 'Vegetables'),
    ('mustard powder', 'Pantry'),
    ('mustard seed', 'Pantry'),
    ('naan bread', 'Bakery'),
    ('natural', 'Snacks'),
    ('natural yogurt', 'Dairy'),
    ('naturally smoked haddock', 'Fish'),
    ('nice baby gem lettuceleave', 'Vegetables'),
    ('nut', 'Pantry'),
    ('nutmeg', 'Pantry'),
    ('nutritional yeast', 'Pantry'),
    ('oil', 'Pantry'),
    ('olive', 'Pantry'),
    ('olive oil', 'Pantry'),
    ('onion', 'Vegetables'),
    ('onion squash', 'Dairy'),
    ('oon', 'Pantry'),
    ('orange', 'Fruit'),
    ('orange curaçao', 'Fruit'),
    ('orange flower water', 'Fruit'),
    ('orange fruit pastille', 'Fruit'),
    ('orange juice', 'Fruit'),
    ('orange liqueur', 'Fruit'),
    ('orange milk chocolate', 'Dairy'),
    ('orange syrup', 'Fruit'),
    ('orange twist', 'Fruit'),
    ('orange water', 'Fruit'),
    ('orange zest', 'Fruit'),
    ('oregano', 'Pantry'),
    ('oreo biscuit', 'Snacks'),
    ('orgeat', 'Snacks'),
    ('oyster', 'Fish'),
    ('oyster sauce', 'Fish'),
    ('paella rice', 'Pantry'),
    ('palm', 'Pantry'),
    ('pancetta', 'Meat'),
    ('papaya', 'Pantry'),
    ('paprika', 'Pantry'),
    ('pared zest', 'Fruit'),
    ('parma ham', 'Meat'),
    ('parmesan', 'Dairy'),
    ('parsley', 'Vegetables'),
    ('parsley leaf', 'Vegetables'),
    ('parsnip', 'Vegetables'),
    ('party sausage', 'Meat'),
    ('passata', 'Pantry'),
    ('pastashape', 'Pantry'),
    ('pea', 'Vegetables'),
    ('peanut', 'Fruit'),
    ('peanut butter', 'Dairy'),
    ('pear', 'Fruit'),
    ('pecan', 'Snacks'),
    ('pecan nut', 'Snacks'),
    ('pecannut', 'Snacks'),
    ('peel', 'Pantry'),
    ('pepper', 'Vegetables'),
    ('peppercorn', 'Vegetables'),
    ('peppermint candy cane', 'Vegetables'),
    ('peppermintextract', 'Vegetables'),
    ('peppersauce', 'Vegetables'),
    ('perry', 'Drinks'),
    ('persimmon', 'Pantry'),
    ('pesto', 'Pantry'),
    ('picked thyme leaf', 'Vegetables'),
    ("pimm's", 'Pantry'),
    ('pinch mixed spice', 'Pantry'),
    ('pinch of mustard powder', 'Pantry'),
    ('pine nut', 'Pantry'),
    ('pineapple', 'Fruit'),
    ('pineapple chunk', 'Fruit'),
    ('pineapple juice', 'Fruit'),
    ('ping', 'Pantry'),
    ('pink peppercorn', 'Vegetables'),
    ('pistachio', 'Snacks'),
    ('pistachio paste', 'Snacks'),
    ('pistachios', 'Snacks'),
    ('plain chocolate', 'Snacks'),
    ('plain dark chocolate', 'Snacks'),
    ('plain flour', 'Pantry'),
    ('plump duck breast', 'Meat'),
    ('plump red chilli', 'Fruit'),
    ('polenta', 'Pantry'),
    ('pomegranate', 'Pantry'),
    ('pomegranate juice', 'Drinks'),
    ('pomegranate molasses', 'Pantry'),
    ('pomegranate seed', 'Pantry'),
    ('poppy seed', 'Pantry'),
    ('porcini mushroom', 'Vegetables'),
    ('pork bellyslice', 'Meat'),
    ('pork fillet', 'Meat'),
    ('pork loin', 'Meat'),
    ('pork mince', 'Meat'),
    ('pork sausage', 'Meat'),
    ('porridge oat', 'Pantry'),
    ('port', 'Pantry'),
    ('portabellini mushroom', 'Vegetables'),
    ('potato', 'Vegetables'),
    ('prawn', 'Fish'),
    ('prawncocktail', 'Fish'),
    ('pre', 'Fish'),
    ('preserving sugar', 'Pantry'),
    ('pretzel', 'Snacks'),
    ('pretzelstick', 'Snacks'),
    ('prosciutto', 'Meat'),
    ('prosecco', 'Drinks'),
    ('prune', 'Fruit'),
    ('puff pastry', 'Bakery'),
    ('pumpkin seed', 'Vegetables'),
    ('puy lentil', 'Vegetables'),
    ('quantity soft royal icing', 'Pantry'),
    ('quick', 'Pantry'),
    ('quince', 'Fruit'),
    ('quince jelly', 'Fruit'),
    ('radicchio', 'Pantry'),
    ('raisin', 'Fruit'),
    ('rapeseed oil', 'Pantry'),
    ('ras el hanout', 'Pantry'),
    ('raspberry', 'Fruit'),
    ('raspberry jam', 'Fruit'),
    ('read', 'Fruit'),
    ('red', 'Fruit'),
    ('red chilli', 'Vegetables'),
    ('red food colouring', 'Pantry'),
    ('red onion', 'Vegetables'),
    ('red pepper', 'Vegetables'),
    ('red wine', 'Drinks'),
    ('redcurrant', 'Fruit'),
    ('redcurrant jelly', 'Fruit'),
    ('reduced', 'Dairy'),
    ('regal', 'Bakery'),
    ('rib of beef', 'Meat'),
    ('rice', 'Pantry'),
    ('rice vinegar', 'Pantry'),
    ('ricotta', 'Dairy'),
    ('rindless streaky bacon', 'Meat'),
    ('rings of dried', 'Fruit'),
    ('risotto rice', 'Pantry'),
    ('roast', 'Vegetables'),
    ('roast turnip', 'Vegetables'),
    ('roasted rhubarb', 'Pantry'),
    ('roasted salted peanut', 'Vegetables'),
    ('roasted vegetable', 'Vegetables'),
    ('rock salt', 'Pantry'),
    ('rocket leaf', 'Pantry'),
    ('rocket leaves', 'Vegetables'),
    ('rolled', 'Meat'),
    ('rolled oat', 'Bakery'),
    ('romaine lettuce', 'Vegetables'),
    ('root ginger', 'Drinks'),
    ('rose harissa', 'Pantry'),
    ('rosemary', 'Vegetables'),
    ('rosewater', 'Drinks'),
    ('roughly crushed white peppercorn', 'Vegetables'),
    ('royal icing mix', 'Pantry'),
    ('royal icing sugar', 'Pantry'),
    ('ruby port', 'Pantry'),
    ('rum', 'Drinks'),
    ('runny honey', 'Pantry'),
    ('rye bread', 'Bakery'),
    ('rye breadloaf', 'Bakery'),
    ('rye cracker', 'Bakery'),
    ('saba', 'Fruit'),
    ('saffron', 'Pantry'),
    ('sage', 'Vegetables'),
    ('salad', 'Pantry'),
    ('salad dressing', 'Pantry'),
    ('salad leaf', 'Pantry'),
    ('salmon', 'Fish'),
    ('salmon fillet', 'Fish'),
    ('salmon slice', 'Fish'),
    ('salmontrimming', 'Fish'),
    ('salt', 'Pantry'),
    ('salted butter', 'Dairy'),
    ('satsuma', 'Drinks'),
    ('sausage', 'Meat'),
    ('sausagemeat', 'Meat'),
    ('sausages', 'Meat'),
    ('savoy', 'Vegetables'),
    ('savoy cabbage', 'Vegetables'),
    ('scallop', 'Fish'),
    ('sea bass', 'Fish'),
    ('sea salt', 'Pantry'),
    ('sea salt flake', 'Pantry'),
    ('sea saltflake', 'Pantry'),
    ('seafood prawn', 'Fish'),
    ('seedless clementine', 'Pantry'),
    ('self', 'Fruit'),
    ('semi', 'Dairy'),
    ('semolina', 'Pantry'),
    ('serrano ham', 'Meat'),
    ('sesame oil', 'Pantry'),
    ('sesame seed', 'Pantry'),
    ('seville orange marmalade', 'Fruit'),
    ('shakes tabasco', 'Pantry'),
    ('shallot', 'Vegetables'),
    ('shaohsing wine', 'Drinks'),
    ('sherry', 'Drinks'),
    ('sherry vinegar', 'Pantry'),
    ('shiitake mushroom', 'Vegetables'),
    ('shortbread dough', 'Bakery'),
    ('shortcrust pastry', 'Bakery'),
    ('shot of espressocoffee', 'Drinks'),
    ('shoulder', 'Meat'),
    ('shredded', 'Meat'),
    ('shredless marmalade', 'Pantry'),
    ('side of salmon', 'Fish'),
    ('side of very fresh salmon', 'Fish'),
    ('sifted icing sugar', 'Pantry'),
    ('silken tofu', 'Pantry'),
    ('silver ball', 'Pantry'),
    ('single cream', 'Dairy'),
    ('skin', 'Pantry'),
    ('skinless', 'Fish'),
    ('slightly salted butter', 'Dairy'),
    ('sloe gin', 'Drinks'),
    ('smarty', 'Snacks'),
    ('smoked', 'Meat'),
    ('smoked mackerel', 'Fish'),
    ('soft black liquorice', 'Drinks'),
    ('soft brown sugar', 'Pantry'),
    ('soft butter', 'Dairy'),
    ('soft cheese', 'Dairy'),
    ('soft dried apricot', 'Fruit'),
    ('soft light brown sugar', 'Pantry'),
    ('soft light muscovado sugar', 'Pantry'),
    ('sour cherry', 'Pantry'),
    ('sourdough', 'Pantry'),
    ('sourdough bread', 'Bakery'),
    ('soured cream', 'Dairy'),
    ('soy sauce', 'Pantry'),
    ('soya cream', 'Dairy'),
    ('spice', 'Pantry'),
    ('spiced rum', 'Drinks'),
    ('spinach', 'Vegetables'),
    ('splash vinegar', 'Pantry'),
    ('sponge cake', 'Pantry'),
    ('spray oil', 'Pantry'),
    ('spring green', 'Pantry'),
    ('spring onion', 'Bakery'),
    ('sprinkle', 'Pantry'),
    ('sprinkling caster sugar', 'Pantry'),
    ('sprout', 'Vegetables'),
    ('square butter muslin', 'Dairy'),
    ('square suit', 'Pantry'),
    ('squash', 'Vegetables'),
    ('squeeze of lime juice', 'Fruit'),
    ('stale french stick', 'Drinks'),
    ('star anise', 'Pantry'),
    ('stem ginger', 'Drinks'),
    ('stem ginger syrup', 'Drinks'),
    ('stem gingerin syrup', 'Drinks'),
    ('stilton', 'Drinks'),
    ('streaky bacon', 'Meat'),
    ('string', 'Drinks'),
    ('strong', 'Meat'),
    ('strong mint', 'Pantry'),
    ('strong plain flour', 'Pantry'),
    ('strong white bread flour', 'Bakery'),
    ('strong white flour', 'Pantry'),
    ('stuffing', 'Pantry'),
    ('suet', 'Pantry'),
    ('sugar', 'Pantry'),
    ('sugar cube', 'Pantry'),
    ('sugar lump', 'Pantry'),
    ('sultana', 'Fruit'),
    ('summer fruit', 'Fruit'),
    ('sundried tomato', 'Vegetables'),
    ('sunflower oil', 'Pantry'),
    ('sunflower seeds', 'Pantry'),
    ('swede', 'Vegetables'),
    ('sweet', 'Drinks'),
    ('sweet cherriesdefrosted', 'Frozen'),
    ('sweet chilli sauce', 'Vegetables'),
    ('sweet potato', 'Vegetables'),
    ('sweet smoked paprika', 'Pantry'),
    ('sweet white wine', 'Fruit'),
    ('sweetcorn', 'Frozen'),
    ('sweets', 'Fruit'),
    ('tabasco', 'Pantry'),
    ('tamari', 'Pantry'),
    ('tamari soy sauce', 'Pantry'),
    ('tangerine', 'Pantry'),
    ('tarragon', 'Pantry'),
    ('teriyaki sauce', 'Pantry'),
    ('thai chilli', 'Vegetables'),
    ('thai fish sauce', 'Fish'),
    ('thai red curry paste', 'Pantry'),
    ('the turkeyneck', 'Meat'),
    ('thumb', 'Drinks'),
    ('thyme', 'Vegetables'),
    ('thyme leaf', 'Vegetables'),
    ('tia maria', 'Drinks'),
    ('tied gammonjoint', 'Pantry'),
    ('tiger prawn', 'Fish'),
    ('toffee sauce', 'Pantry'),
    ('tomato', 'Vegetables'),
    ('tomato juice', 'Vegetables'),
    ('tomato ketchup', 'Vegetables'),
    ('tomato purée', 'Vegetables'),
    ('tomatoeson the vine', 'Vegetables'),
    ('tonic water', 'Drinks'),
    ('top', 'Dairy'),
    ('toppings of your choice', 'Pantry'),
    ('tortilla wraps', 'Pantry'),
    ('treacle', 'Pantry'),
    ('trimming', 'Bakery'),
    ('trinket', 'Vegetables'),
    ('triple sec', 'Pantry'),
    ('tropical dried fruit medley', 'Fruit'),
    ('truffle', 'Pantry'),
    ('truffle oil', 'Pantry'),
    ('truffleshaving', 'Pantry'),
    ('tuna', 'Fish'),
    ('turkey', 'Meat'),
    ('turkey breast', 'Meat'),
    ('turkey breast fillet', 'Meat'),
    ('turkey breast steak', 'Meat'),
    ('turkey crown', 'Meat'),
    ('turkey mince', 'Meat'),
    ('turkeyneck', 'Meat'),
    ('turkish delight', 'Drinks'),
    ('turmeric', 'Pantry'),
    ('turnip', 'Vegetables'),
    ('turquoise food colouring', 'Pantry'),
    ('tzatziki', 'Pantry'),
    ('uette', 'Pantry'),
    ('uncooked ham', 'Meat'),
    ('unpeeled salad', 'Vegetables'),
    ("unrefined billington's icing sugar", 'Drinks'),
    ('unsalted butter', 'Dairy'),
    ('unscented coconut oil', 'Fruit'),
    ('unsmoked boneless gammon', 'Pantry'),
    ('unsmoked boneless gammonjoint', 'Pantry'),
    ('unsmoked leg of gammon', 'Pantry'),
    ('vanilla', 'Pantry'),
    ('vanilla bean paste', 'Vegetables'),
    ('vanilla essence', 'Pantry'),
    ('vanilla extract', 'Pantry'),
    ('vanilla ice cream', 'Dairy'),
    ('vanilla pod', 'Pantry'),
    ('veal stock', 'Meat'),
    ('veg stock', 'Drinks'),
    ('vegan white wine vinegar', 'Drinks'),
    ('vegetable', 'Vegetables'),
    ('vegetable bouillon powder', 'Drinks'),
    ('vegetable oil', 'Pantry'),
    ('vegetable stock', 'Drinks'),
    ('vegetable stock cube', 'Drinks'),
    ('vegetable stockcube', 'Drinks'),
    ('vegetarian cheddar', 'Dairy'),
    ('venison loin', 'Meat'),
    ('venison sausage', 'Meat'),
    ('vermouth', 'Drinks'),
    ('vinaigrette', 'Pantry'),
    ('vine', 'Vegetables'),
    ('vine tomato', 'Vegetables'),
    ('virgin olive oil', 'Drinks'),
    ('vodka', 'Drinks'),
    ('walnut', 'Snacks'),
    ('walnut oil', 'Snacks'),
    ('walnut whip', 'Snacks'),
    ('water', 'Drinks'),
    ('watercress', 'Vegetables'),
    ('wedge of camembert', 'Pantry'),
    ('whisky', 'Drinks'),
    ('white bread', 'Bakery'),
    ('white chicory', 'Pantry'),
    ('white chocolate', 'Snacks'),
    ('white chocolate button', 'Snacks'),
    ('white wine', 'Drinks'),
    ('wholegrain mustard', 'Pantry'),
    ('wholemeal flour', 'Pantry'),
    ('wholemeal plain flour', 'Pantry'),
    ('wholemeal vegan breadcrumb', 'Bakery'),
    ('wild mushroom', 'Vegetables'),
    ('wild rocket', 'Pantry'),
    ('williams pear', 'Fruit'),
    ('wine', 'Drinks'),
    ('wine vinegar', 'Drinks'),
    ('winter salad leaf', 'Pantry'),
    ('worcestershire sauce', 'Pantry'),
    ('writing icing', 'Pantry'),
    ('yeast', 'Pantry'),
    ('yogurt', 'Dairy'),
    ('young spinachleave', 'Vegetables'),
    ("za'atar", 'Pantry'),
    ]

    Ingredient.objects.filter(name__in=ingredient_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_load_categories'),
    ]

    operations = [
        migrations.RunPython(load_ingredients, unload_ingredients),
    ]
